# Setting Everything Up

In [1]:
import pandas as pd

In [2]:
# I can give a number or use None to remove maximum ceiling & display all columns
pd.options.display.max_columns = None

# # I want to be able to see the entire narrative, so remove the maximum width for each column
# pd.options.display.max_colwidth = None

# pd.options.display.float_format = '{:,.0f}'.format

%matplotlib inline

In [3]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (8, 8)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

In [4]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [5]:
%%R

# My commonly used R imports

require('tidyverse')

R[write to console]: Loading required package: tidyverse

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [6]:
%%R

library(jpeg)
library(RColorBrewer)

In [7]:
%%R
library(plotly)
library(ggrepel)
#for timeline plotting

R[write to console]:
Attaching package: ‘plotly’


R[write to console]: The following object is masked from ‘package:ggplot2’:

    last_plot


R[write to console]: The following object is masked from ‘package:stats’:

    filter


R[write to console]: The following object is masked from ‘package:graphics’:

    layout

# From Office Hours

In [10]:
df_edu_plus_income_for_analysis=pd.read_csv("df_edu_plus_income_for_analysis.csv", thousands=",", dtype={"total_revenue_2021_22_plus": float})

In [12]:
df_edu_plus_income_for_analysis

    Unnamed: 0  Unnamed: 0_x County_slash_Sub_County_x  \
0            0             0                   MOMBASA
1            1             7                     KWALE
2            2            13                    KILIFI
3            3            23                TANA RIVER
4            4            27                      LAMU
5            5            30              TAITA/TAVETA
6            6            35                   GARISSA
7            7            43                     WAJIR
8            8            52                   MANDERA
9            9            60                  MARSABIT
10          10            68                    ISIOLO
11          11            72                      MERU
12          12           585             THARAKA-NITHI
13          13           591                      EMBU
14          14           597                     KITUI
15          15           616                  MACHAKOS
16          16           626                   MAKUENI
17          17           636                 NYANDARUA
18          18           644                     NYERI
19          19           669                 KIRINYAGA
20          20           675                  MURANG'A
21          21           684                    KIAMBU
22          22           698                   TURKANA
23          23           706                WEST POKOT
24          24           712                   SAMBURU
25          25           716               TRANS NZOIA
26          26           722               UASIN GISHU
27          27           729           ELGEYO/MARAKWET
28          28           734                     NANDI
29          29           741                   BARINGO
30          30           749                  LAIKIPIA
31          31           755                    NAKURU
32          32           767                     NAROK
33          33           775                   KAJIADO
34          34           782                   KERICHO
35          35           789                     BOMET
36          36           795                  KAKAMEGA
37          37           809                    VIHIGA
38          38           816                   BUNGOMA
39          39           828                     BUSIA
40          41           836                     SIAYA
41          43           843                    KISUMU
42          44           851                  HOMA BAY
43          45           860                    MIGORI
44          46           869                     KISII
45          47           881                   NYAMIRA
46          48           887              NAIROBI CITY

    lighting_Conventional_Households  lighting_Mains_Electricity  \
0                             376295                        85.9
1                             172802                        31.5
2                             297990                        38.5
3                              66984                        25.6
4                              34231                        43.2
5                              94468                        47.6
6                             138940                        23.5
7                             126878                        14.1
8                             123954                        15.7
9                              76689                        21.3
10                             53217                        40.6
11                            423931                        40.2
12                            109450                        34.7
13                            182427                        47.0
14                            261814                        17.1
15                            399523                        48.3
16                            243979                        20.4
17                            178224                        41.3
18                            244564                        71.8
19                            203576                        65.3
20                            317496                        60.5
21                            792333                        91.7
22                            162627                         8.6
23                            115761                        11.8
24                             63951                        14.8
25                            222989                        37.9
26                            301110                        63.8
27                             99119                        24.3
28                            199040                        30.7
29                            141877                        28.3
30                            145776                        42.2
31                            598237                        64.4
32                            238115                        19.7
33                            313218                        67.4
34                            205932                        44.9
35                            187230                        22.1
36                            432284                        25.1
37                            143288                        38.4
38                            357714                        21.6
39                            197944                        26.1
40                            249341                        19.7
41                            296846                        52.6
42                            260290                        18.4
43                            238133                        23.3
44                            307254                        39.3
45                            150499                        42.9
46                           1494676                        96.5

    lighting_Paraffin_Pressure_lamp  lighting_Paraffin_Lantern  \
0                               0.5                        2.7
1                               0.5                        6.0
2                               0.6                        6.1
3                               0.2                        2.4
4                               0.2                        3.6
5                               0.3                       10.7
6                               0.2                        0.7
7                               0.1                        0.6
8                               0.2                        0.5
9                               0.2                        2.7
10                              0.3                        3.8
11                              0.5                       11.0
12                              0.4                        9.0
13                              0.4                        8.0
14                              0.5                       13.8
15                              0.6                       11.6
16                              0.7                       16.0
17                              0.4                       15.0
18                              0.4                        8.1
19                              0.4                        9.3
20                              0.5                       12.5
21                              0.2                        2.6
22                              0.1                        0.9
23                              0.2                        4.7
24                              0.3                        3.3
25                              0.4                        9.8
26                              0.2                        5.0
27                              0.3                        4.5
28                              0.3                        7.1
29                              0.3                        6.6
30                              0.3                        8.4
31                              0.2                        5.8
32                              0.2                        4.1
33                              0.3                        3.9
34                              0.2                        5.9
35                              0.2                        4.9
36                              0.3                        8.8
37                              0.3                        8.7
38                              0.4                       11.4
39                              0.3                        8.7
40                              0.2                        6.7
41                              0.3                        5.2
42                              0.3                        6.9
43                              0.3                        9.0
44                              0.4                       13.6
45                              0.5                       16.1
46                              0.1                        0.8

    lighting_Paraffin_Tin_Lamp  lighting_Gas_Lamp  lighting_Wood  \
0                          6.3                0.1            0.0
1                         29.5                0.2            1.7
2                         26.7                0.1            1.3
3                          7.1                0.5            6.8
4                          7.2                0.1            1.4
5                          9.6                0.0            0.2
6                          1.5                2.8           11.9
7                          0.9                2.8           15.4
8                          1.0                2.6           26.8
9                          2.8                1.6           14.2
10                         3.7                1.2            6.7
11                        13.9                0.2            1.5
12                        13.1                0.1            2.1
13                        11.8                0.1            0.4
14                         9.4                0.2            1.9
15                         7.7                0.1            0.2
16                        10.0                0.1            0.3
17                         8.1                0.1            0.1
18                         8.1                0.1            0.1
19                        12.5                0.0            0.1
20                        14.3                0.1            0.1
21                         2.2                0.0            0.0
22                         1.8                0.3           49.1
23                         5.1                0.2           31.7
24                         5.5                0.3           36.3
25                        16.0                0.1            0.7
26                         4.4                0.1            0.3
27                         3.9                0.1            9.9
28                        11.9                0.1            0.3
29                         4.8                0.1           18.2
30                         9.1                0.1            3.8
31                         4.4                0.1            0.4
32                         5.6                0.2            5.5
33                         5.0                0.1            1.0
34                         6.3                0.1            0.3
35                         3.2                0.1            0.8
36                        20.5                0.1            0.4
37                        28.2                0.0            0.2
38                        18.5                0.2            0.9
39                        18.3                0.1            0.4
40                        17.1                0.1            0.2
41                        12.5                0.1            0.2
42                        14.4                0.2            0.6
43                        17.3                0.2            0.8
44                        20.1                0.1            0.7
45                        19.5                0.1            0.9
46                         0.8                0.0            0.0

   lighting_Solar_and_Solar_Torch_and_Battery_Torch  lighting_Solar  \
0                                       1.5 0.4 0.3             1.5
1                                      22.8 2.7 3.9            22.8
2                                      20.0 2.4 2.9            20.0
3                                    20.9 12.1 21.7            20.9
4                                      28.3 5.8 8.3            28.3
5                                      24.4 2.8 2.8            24.4
6                                    12.7 10.9 32.1            12.7
7                                    11.6 11.2 42.2            11.6
8                                      9.9 8.2 34.1             9.9
9                                    15.1 12.6 28.4            15.1
10                                     9.1 9.0 24.6             9.1
11                                     18.8 3.6 8.3            18.8
12                                    17.1 3.9 18.2            17.1
13                                     21.1 2.8 6.6            21.1
14                                    37.3 6.7 11.7            37.3
15                                     25.6 2.9 0.9            25.6
16                                     44.0 4.2 2.9            44.0
17                                     28.4 2.7 1.1            28.4
18                                      8.4 1.2 0.7             8.4
19                                      8.5 1.2 0.9             8.5
20                                      9.2 1.2 0.5             9.2
21                                      1.2 0.3 0.2             1.2
22                                    6.2 12.1 18.2             6.2
23                                   15.1 11.8 18.6            15.1
24                                    13.3 9.6 15.7            13.3
25                                     23.9 7.5 1.0            23.9
26                                     14.9 8.5 0.8            14.9
27                                    25.7 23.7 6.2            25.7
28                                    28.6 17.8 1.4            28.6
29                                    21.9 10.1 8.3            21.9
30                                     26.4 5.3 2.3            26.4
31                                     14.5 6.5 1.2            14.5
32                                    37.7 20.1 4.5            37.7
33                                     15.5 3.6 1.4            15.5
34                                    20.9 17.8 1.5            20.9
35                                    33.5 30.1 2.7            33.5
36                                     36.7 6.2 0.3            36.7
37                                     20.0 3.2 0.3            20.0
38                                     36.4 8.2 0.6            36.4
39                                     37.9 5.9 0.5            37.9
40                                     50.8 2.8 0.4            50.8
41                                     26.2 1.6 0.2            26.2
42                                     52.5 3.2 0.4            52.5
43                                     41.3 3.6 0.7            41.3
44                                     20.5 3.1 0.4            20.5
45                                     15.5 2.7 0.6            15.5
46                                      0.2 0.1 0.1             0.2

    lighting_Torch_slash_Spotlight_Solar_Charged  \
0                                            0.4
1                                            2.7
2                                            2.4
3                                           12.1
4                                            5.8
5                                            2.8
6                                           10.9
7                                           11.2
8                                            8.2
9                                           12.6
10                                           9.0
11                                           3.6
12                                           3.9
13                                           2.8
14                                           6.7
15                                           2.9
16                                           4.2
17                                           2.7
18                                           1.2
19                                           1.2
20                                           1.2
21                                           0.3
22                                          12.1
23                                          11.8
24                                           9.6
25                                           7.5
26                                           8.5
27                                          23.7
28                                          17.8
29                                          10.1
30                                           5.3
31                                           6.5
32                                          20.1
33                                           3.6
34                                          17.8
35                                          30.1
36                                           6.2
37                                           3.2
38                                           8.2
39                                           5.9
40                                           2.8
41                                           1.6
42                                           3.2
43                                           3.6
44                                           3.1
45                                           2.7
46                                           0.1

    lighting_Torch_slash_Spotlight_Dry_cells  lighting_Candle  \
0                                        0.3              2.2
1                                        3.9              0.9
2                                        2.9              1.2
3                                       21.7              2.3
4                                        8.3              1.4
5                                        2.8              1.2
6                                       32.1              1.4
7                                       42.2              0.6
8                                       34.1              0.8
9                                       28.4              0.9
10                                      24.6              0.7
11                                       8.3              1.5
12                                      18.2              1.1
13                                       6.6              1.5
14                                      11.7              0.9
15                                       0.9              1.8
16                                       2.9              1.0
17                                       1.1              1.6
18                                       0.7              1.0
19                                       0.9              1.5
20                                       0.5              0.9
21                                       0.2              1.5
22                                      18.2              1.8
23                                      18.6              0.7
24                                      15.7              0.6
25                                       1.0              2.0
26                                       0.8              1.7
27                                       6.2              1.1
28                                       1.4              1.1
29                                       8.3              1.1
30                                       2.3              1.2
31                                       1.2              1.8
32                                       4.5              1.4
33                                       1.4              1.7
34                                       1.5              1.4
35                                       2.7              0.8
36                                       0.3              0.8
37                                       0.3              0.5

In [13]:
%%R -i df_edu_plus_income_for_analysis
# guide for multivariable regression
school_density_variable<-(df_edu_plus_income_for_analysis$population/df_edu_plus_income_for_analysis$number_of_schools)/df_edu_plus_income_for_analysis$land_area_km_sq

model <- lm(left_school_over_left_before_and_after_as_pct ~total_revenue_2021_22_plus + average_school_size+ pupil_textbook_ratio  + public_over_overall_enrolment_as_pct + school_density_variable, df_edu_plus_income_for_analysis)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    total_revenue_2021_22_plus + average_school_size + pupil_textbook_ratio +
        public_over_overall_enrolment_as_pct + school_density_variable,
    data = df_edu_plus_income_for_analysis)

Residuals:
     Min       1Q   Median       3Q      Max
-15.4850  -5.5526   0.1198   5.3399  18.5502

Coefficients:
                                       Estimate Std. Error t value Pr(>|t|)
(Intercept)                           3.422e-01  1.764e+01   0.019 0.984625
total_revenue_2021_22_plus           -4.106e-04  2.932e-04  -1.401 0.169060
average_school_size                   3.834e-02  2.098e-02   1.827 0.075158 .
pupil_textbook_ratio                 -1.349e+01  1.245e+01  -1.084 0.285044
public_over_overall_enrolment_as_pct  5.135e-01  1.438e-01   3.572 0.000941 ***
school_density_variable               5.437e+00  4.486e+00   1.212 0.232667
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 7.825 on 40 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.4877,	Adjusted R-squared:  0.4237
F-statistic: 7.616 on 5 and 40 DF,  p-value: 4.189e-05

In [14]:
%%R 
# guide for multivariable regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ log(average_school_size) + public_over_overall_enrolment_as_pct + with_national_grid_pct + lighting_Mains_Electricity + drinking_water_Piped_into_dwelling + Use_of_Internet_pct + Seeking_Work_No_Work_Available_over_Total_Total_pct, df_edu_plus_income_for_analysis)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    log(average_school_size) + public_over_overall_enrolment_as_pct +
        with_national_grid_pct + lighting_Mains_Electricity +
        drinking_water_Piped_into_dwelling + Use_of_Internet_pct +
        Seeking_Work_No_Work_Available_over_Total_Total_pct,
    data = df_edu_plus_income_for_analysis)

Residuals:
     Min       1Q   Median       3Q      Max
-10.7899  -2.5129   0.2749   2.4966   9.3932

Coefficients:
                                                     Estimate Std. Error
(Intercept)                                         46.432817  21.174629
log(average_school_size)                             0.709107   3.047412
public_over_overall_enrolment_as_pct                -0.112712   0.138585
with_national_grid_pct                              -0.250094   0.036159
lighting_Mains_Electricity                          -0.007955   0.103491
drinking_water_Piped_into_dwelling                   0.232522   0.155555
Use_of_Internet_pct                                 -0.946091   0.209998
Seeking_Work_No_Work_Available_over_Total_Total_pct  2.331782   0.244633
                                                    t value Pr(>|t|)
(Intercept)                                           2.193   0.0343 *
log(average_school_size)                              0.233   0.8172
public_over_overall_enrolment_as_pct                 -0.813   0.4210
with_national_grid_pct                               -6.916 2.79e-08 ***
lighting_Mains_Electricity                           -0.077   0.9391
drinking_water_Piped_into_dwelling                    1.495   0.1430
Use_of_Internet_pct                                  -4.505 5.88e-05 ***
Seeking_Work_No_Work_Available_over_Total_Total_pct   9.532 9.77e-12 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.465 on 39 degrees of freedom
Multiple R-squared:  0.9593,	Adjusted R-squared:  0.952
F-statistic: 131.5 on 7 and 39 DF,  p-value: < 2.2e-16

In [15]:
%%R -o df_edu_plus_income_for_analysis_residuals
#access to education
# guide for multivariable regression

df_edu_plus_income_for_analysis_residuals<- df_edu_plus_income_for_analysis %>% 
    mutate(residuals=resid(model),
          residuals_z=(residuals-mean(residuals))/sd(residuals))

In [16]:
df_edu_plus_income_for_analysis_residuals.sort_values(by="residuals")[["County_slash_Sub_County_x","residuals", "residuals_z" ]]

   County_slash_Sub_County_x  residuals  residuals_z
24                   SAMBURU -10.789907    -2.624749
0                    MOMBASA  -7.981007    -1.941457
14                     KITUI  -5.486877    -1.334736
16                   MAKUENI  -5.206747    -1.266591
3                 TANA RIVER  -5.166828    -1.256881
22                   TURKANA  -5.072049    -1.233825
12             THARAKA-NITHI  -4.255100    -1.035094
4                       LAMU  -4.134615    -1.005785
2                     KILIFI  -3.704877    -0.901247
25               TRANS NZOIA  -3.663169    -0.891101
6                    GARISSA  -3.345439    -0.813810
26               UASIN GISHU  -2.657439    -0.646448
11                      MERU  -2.368425    -0.576142
32                     NAROK  -1.943708    -0.472826
27           ELGEYO/MARAKWET  -1.755844    -0.427126
20                  MURANG'A  -1.730323    -0.420918
38                   BUNGOMA  -1.567584    -0.381330
13                      EMBU  -1.227610    -0.298628
37                    VIHIGA  -1.024091    -0.249120
33                   KAJIADO  -0.564507    -0.137322
10                    ISIOLO  -0.530521    -0.129054
44                     KISII  -0.471886    -0.114791
15                  MACHAKOS  -0.388067    -0.094401
42                  HOMA BAY   0.274894     0.066871
36                  KAKAMEGA   0.729130     0.177368
40                     SIAYA   0.901049     0.219189
31                    NAKURU   0.980277     0.238462
34                   KERICHO   1.022220     0.248665
41                    KISUMU   1.033833     0.251490
28                     NANDI   1.090448     0.265262
5               TAITA/TAVETA   1.153733     0.280657
19                 KIRINYAGA   1.340073     0.325986
1                      KWALE   2.033079     0.494566
45                   NYAMIRA   2.264940     0.550969
39                     BUSIA   2.455448     0.597311
35                     BOMET   2.537710     0.617322
18                     NYERI   2.913909     0.708837
43                    MIGORI   2.987363     0.726705
30                  LAIKIPIA   3.131370     0.761736
21                    KIAMBU   3.250512     0.790718
17                 NYANDARUA   3.567425     0.867810
46              NAIROBI CITY   4.179851     1.016789
29                   BARINGO   5.531153     1.345506
23                WEST POKOT   6.048550     1.471368
7                      WAJIR   7.862406     1.912606
9                   MARSABIT   8.354064     2.032207
8                    MANDERA   9.393185     2.284983

In [19]:
%%R 
# guide for multivariable regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ with_national_grid_pct + drinking_water_Piped_into_dwelling + Use_of_Internet_pct + Seeking_Work_No_Work_Available_over_Total_Total_pct, df_edu_plus_income_for_analysis)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    with_national_grid_pct + Use_of_Internet_pct + Seeking_Work_No_Work_Available_over_Total_Total_pct,
    data = df_edu_plus_income_for_analysis)

Residuals:
     Min       1Q   Median       3Q      Max
-10.9824  -2.3951  -0.1311   2.3462   9.3555

Coefficients:
                                                    Estimate Std. Error t value
(Intercept)                                         37.86118    3.01773  12.546
with_national_grid_pct                              -0.24506    0.03445  -7.113
Use_of_Internet_pct                                 -0.75845    0.08988  -8.439
Seeking_Work_No_Work_Available_over_Total_Total_pct  2.43199    0.19657  12.372
                                                    Pr(>|t|)
(Intercept)                                         5.77e-16 ***
with_national_grid_pct                              8.83e-09 ***
Use_of_Internet_pct                                 1.14e-10 ***
Seeking_Work_No_Work_Available_over_Total_Total_pct 9.26e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.419 on 43 degrees of freedom
Multiple R-squared:  0.9561,	Adjusted R-squared:  0.953
F-statistic:   312 on 3 and 43 DF,  p-value: < 2.2e-16

In [24]:
%%R 
# guide for multivariable regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ with_national_grid_pct, df_edu_plus_income_for_analysis)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    with_national_grid_pct, data = df_edu_plus_income_for_analysis)

Residuals:
     Min       1Q   Median       3Q      Max
-26.4699  -2.3906   0.6483   2.7325  26.2142

Coefficients:
                       Estimate Std. Error t value Pr(>|t|)
(Intercept)            65.34859    3.77874   17.29   <2e-16 ***
with_national_grid_pct -0.58811    0.04559  -12.90   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 9.51 on 45 degrees of freedom
Multiple R-squared:  0.7871,	Adjusted R-squared:  0.7824
F-statistic: 166.4 on 1 and 45 DF,  p-value: < 2.2e-16